extern crate halo2;

use std::marker::PhantomData;

use halo2::{
    arithmetic::FieldExt,
    circuit::{layouter::SingleConfigLayouter, Cell, Config, Layouter},
    dev::VerifyFailure,
    plonk::{
        Advice, Assignment, Circuit, Column, ConstraintSystem, Error, Instance, Permutation,
        Selector,
    },
    poly::Rotation,
};

#[derive(Clone)]
struct Number<F: FieldExt> {
    cell: Cell,
    value: Option<F>,
}

trait NumericInstructions: Config {
    /// Variable representing a number.
    type Num;

    /// Loads a number into the circuit as a private input.
    fn load_private(
        layouter: &mut impl Layouter<Self>,
        a: Option<Self::Field>,
    ) -> Result<Self::Num, Error>;

    /// Returns `c = a + b`.
    fn add<CS: Assignment<Self::Field>>(
        layouter: &mut SingleConfigLayouter<'_, Self, CS>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error>;

    /// Returns `c = a * b`.
    fn mul<CS: Assignment<Self::Field>>(
        layouter: &mut SingleConfigLayouter<'_, Self, CS>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error>;

    /// Exposes a number as a public input to the circuit.
    fn expose_public(layouter: &mut impl Layouter<Self>, num: Self::Num) -> Result<(), Error>;
}
// ANCHOR_END: instructions

// ANCHOR: mul-instructions
trait MulInstructions: Config {
    /// Variable representing a number.
    type Num;

    /// Returns `c = a * b`.
    fn mul(
        layouter: &mut impl Layouter<Self>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error>;
}
// ANCHOR_END: mul-instructions

// ANCHOR: add-instructions
trait AddInstructions: Config {
    /// Variable representing a number.
    type Num;

    /// Returns `c = a + b`.
    fn add(
        layouter: &mut impl Layouter<Self>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error>;
}
// ANCHOR_END: add-instructions

// ANCHOR: config
/// The config that will implement our instructions! Configs do not store any persistent
/// state themselves, and usually only contain type markers if necessary.
struct FieldConfig<F: FieldExt> {
    _marker: PhantomData<F>,
}

impl<F: FieldExt> Config for FieldConfig<F> {
    type Configured = FieldConfigured;
    type Loaded = ();
    type Field = F;
    fn load(layouter: &mut impl Layouter<Self>) -> Result<Self::Loaded, Error> {
        Ok(())
    }
}
// ANCHOR_END: config

// ANCHOR: configured
/// Configured state is stored in a separate config struct. This is generated by the config
/// during configuration, and then handed to the `Layouter`, which makes it available
/// to the config when it needs to implement its instructions.
#[derive(Clone, Debug)]
struct FieldConfigured {
    s_pub: Selector,
    perm: Permutation,
    advice: [Column<Advice>; 2],
    add_configured: AddConfigured,
    mul_configured: MulConfigured,
}

impl<F: FieldExt> FieldConfig<F> {
    fn configure(
        meta: &mut ConstraintSystem<F>,
        advice: [Column<Advice>; 2],
        instance: Column<Instance>,
    ) -> FieldConfigured {
        let perm = Permutation::new(
            meta,
            &advice
                .iter()
                .map(|column| (*column).into())
                .collect::<Vec<_>>(),
        );
        let s_pub = meta.selector();
        let s_add = meta.selector();
        let s_mul = meta.selector();

        let add_configured = AddConfig::configure(meta, perm.clone(), advice, s_add);
        let mul_configured = MulConfig::configure(meta, perm.clone(), advice, s_mul);

        FieldConfigured {
            s_pub,
            perm,
            advice,
            add_configured,
            mul_configured,
        }
    }
}
// ANCHOR_END: configured

impl<F: FieldExt> NumericInstructions for FieldConfig<F> {
    type Num = Number<F>;

    fn load_private(
        layouter: &mut impl Layouter<Self>,
        value: Option<F>,
    ) -> Result<Self::Num, Error> {
        let configured = layouter.configured().clone();
        let mut num = None;
        layouter.assign_region(
            || "load private",
            |mut region| {
                let cell = region.assign_advice(
                    || "private input",
                    configured.advice[0],
                    0,
                    || value.ok_or(Error::SynthesisError),
                )?;
                num = Some(Number { cell, value });
                Ok(())
            },
        )?;
        Ok(num.unwrap())
    }

    fn add<CS: Assignment<Self::Field>>(
        layouter: &mut SingleConfigLayouter<'_, Self, CS>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error> {
        let add_configured = layouter.configured().add_configured.clone();
        let mut add_layouter =
            SingleConfigLayouter::<'_, Self, CS>::sublayouter(layouter.cs, add_configured)?;
        AddConfig::<F>::add(&mut add_layouter, a, b)
    }

    fn mul<CS: Assignment<Self::Field>>(
        layouter: &mut SingleConfigLayouter<'_, Self, CS>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error> {
        let mul_configured = layouter.configured().mul_configured.clone();
        let mut mul_layouter =
            SingleConfigLayouter::<'_, Self, CS>::sublayouter(layouter.cs, mul_configured)?;
        MulConfig::<F>::mul(&mut mul_layouter, a, b)
    }

    fn expose_public(layouter: &mut impl Layouter<Self>, num: Self::Num) -> Result<(), Error> {
        let configured = layouter.configured().clone();
        layouter.assign_region(
            || "expose public",
            |mut region| {
                // Enable the public-input gate.
                configured.s_pub.enable(&mut region, 0)?;

                // Load the output into the correct advice column.
                let out = region.assign_advice(
                    || "public advice",
                    configured.advice[1],
                    0,
                    || num.value.ok_or(Error::SynthesisError),
                )?;
                region.constrain_equal(&configured.perm, num.cell, out)?;

                // We don't assign to the instance column inside the circuit;
                // the mapping of public inputs to cells is provided to the prover.
                Ok(())
            },
        )
    }
}
// ANCHOR_END: instructions-impl

// ANCHOR: add-config
/// The config that will implement AddInstructions.
#[derive(Clone, Debug)]
struct AddConfig<F: FieldExt> {
    _marker: PhantomData<F>,
}

impl<F: FieldExt> Config for AddConfig<F> {
    type Configured = AddConfigured;
    type Loaded = ();
    type Field = F;
    fn load(layouter: &mut impl Layouter<Self>) -> Result<Self::Loaded, Error> {
        Ok(())
    }
}
// ANCHOR_END: add-config

// ANCHOR: add-configured
#[derive(Clone, Debug)]
struct AddConfigured {
    perm: Permutation,

    /// For this core, we will use two advice columns to implement our instructions.
    /// These are also the columns through which we communicate with other parts of
    /// the circuit.
    advice: [Column<Advice>; 2],

    // We need a selector to enable the addition gate, so that we aren't placing
    // any constraints on cells where `AddInstructions::add` is not being used.
    // This is important when building larger circuits, where columns are used by
    // multiple sets of instructions.
    s_add: Selector,
}

impl<F: FieldExt> AddConfig<F> {
    fn configure(
        meta: &mut ConstraintSystem<F>,
        perm: Permutation,
        advice: [Column<Advice>; 2],
        s_add: Selector,
    ) -> AddConfigured {
        // Define our addition gate!
        meta.create_gate("add", |meta| {
            // To implement addition, we need three advice cells and a selector
            // cell. We arrange them like so:
            //
            // | a0  | a1  | s_add |
            // |-----|-----|-------|
            // | lhs | rhs | s_add |
            // | out |     |       |
            //
            // Gates may refer to any relative offsets we want, but each distinct
            // offset adds a cost to the proof. The most common offsets are 0 (the
            // current row), 1 (the next row), and -1 (the previous row), for which
            // `Rotation` has specific constructors.
            let lhs = meta.query_advice(advice[0], Rotation::cur());
            let rhs = meta.query_advice(advice[1], Rotation::cur());
            let out = meta.query_advice(advice[0], Rotation::next());
            let s_add = meta.query_selector(s_add, Rotation::cur());

            // The polynomial expression returned from `create_gate` will be
            // constrained by the proving system to equal zero. Our expression
            // has the following properties:
            // - When s_add = 0, any value is allowed in lhs, rhs, and out.
            // - When s_add != 0, this constrains lhs + rhs = out.
            s_add * (lhs + rhs + out * -F::one())
        });

        AddConfigured {
            perm,
            advice,
            s_add,
        }
    }
}
// ANCHOR_END: add-configured

// ANCHOR: add-instructions-impl
impl<F: FieldExt> AddInstructions for AddConfig<F> {
    type Num = Number<F>;

    fn add(
        layouter: &mut impl Layouter<Self>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error> {
        let configured = layouter.configured().clone();

        let mut out = None;
        layouter.assign_region(
            || "mul",
            |mut region| {
                // We only want to use a single addition gate in this region,
                // so we enable it at region offset 0; this means it will constrain
                // cells at offsets 0 and 1.
                configured.s_add.enable(&mut region, 0)?;

                // The inputs we've been given could be located anywhere in the circuit,
                // but we can only rely on relative offsets inside this region. So we
                // assign new cells inside the region and constrain them to have the
                // same values as the inputs.
                let lhs = region.assign_advice(
                    || "lhs",
                    configured.advice[0],
                    0,
                    || a.value.ok_or(Error::SynthesisError),
                )?;
                let rhs = region.assign_advice(
                    || "rhs",
                    configured.advice[1],
                    0,
                    || b.value.ok_or(Error::SynthesisError),
                )?;
                region.constrain_equal(&configured.perm, a.cell, lhs)?;
                region.constrain_equal(&configured.perm, b.cell, rhs)?;

                // Now we can assign the addition result into the output position.
                let value = a.value.and_then(|a| b.value.map(|b| a + b));
                let cell = region.assign_advice(
                    || "lhs + rhs",
                    configured.advice[0],
                    1,
                    || value.ok_or(Error::SynthesisError),
                )?;

                // Finally, we return a variable representing the output,
                // to be used in another part of the circuit.
                out = Some(Number { cell, value });
                Ok(())
            },
        )?;

        Ok(out.unwrap())
    }
}
// ANCHOR_END: add-instructions-impl

// ANCHOR: mul-config
/// The config that will implement MulInstructions.
#[derive(Clone, Debug)]
struct MulConfig<F: FieldExt> {
    _marker: PhantomData<F>,
}

impl<F: FieldExt> Config for MulConfig<F> {
    type Configured = MulConfigured;
    type Loaded = ();
    type Field = F;
    fn load(layouter: &mut impl Layouter<Self>) -> Result<Self::Loaded, Error> {
        Ok(())
    }
}
// ANCHOR_END: mul-config

// ANCHOR: mul-configured
#[derive(Clone, Debug)]
struct MulConfigured {
    perm: Permutation,

    /// For this core, we will use two advice columns to implement our instructions.
    /// These are also the columns through which we communicate with other parts of
    /// the circuit.
    advice: [Column<Advice>; 2],

    // We need a selector to enable the multiplication gate, so that we aren't placing
    // any constraints on cells where `MulInstructions::mul` is not being used.
    // This is important when building larger circuits, where columns are used by
    // multiple sets of instructions.
    s_mul: Selector,
}

impl<F: FieldExt> MulConfig<F> {
    fn configure(
        meta: &mut ConstraintSystem<F>,
        perm: Permutation,
        advice: [Column<Advice>; 2],
        s_mul: Selector,
    ) -> MulConfigured {
        // Define our multiplication gate!
        meta.create_gate("mul", |meta| {
            // To implement multiplication, we need three advice cells and a selector
            // cell. We arrange them like so:
            //
            // | a0  | a1  | s_mul |
            // |-----|-----|-------|
            // | lhs | rhs | s_mul |
            // | out |     |       |
            //
            // Gates may refer to any relative offsets we want, but each distinct
            // offset adds a cost to the proof. The most common offsets are 0 (the
            // current row), 1 (the next row), and -1 (the previous row), for which
            // `Rotation` has specific constructors.
            let lhs = meta.query_advice(advice[0], Rotation::cur());
            let rhs = meta.query_advice(advice[1], Rotation::cur());
            let out = meta.query_advice(advice[0], Rotation::next());
            let s_mul = meta.query_selector(s_mul, Rotation::cur());

            // The polynomial expression returned from `create_gate` will be
            // constrained by the proving system to equal zero. Our expression
            // has the following properties:
            // - When s_mul = 0, any value is allowed in lhs, rhs, and out.
            // - When s_mul != 0, this constrains lhs * rhs = out.
            s_mul * (lhs * rhs + out * -F::one())
        });

        MulConfigured {
            perm,
            advice,
            s_mul,
        }
    }
}
// ANCHOR_END: mul-configured

// ANCHOR: mul-instructions-impl
impl<F: FieldExt> MulInstructions for MulConfig<F> {
    type Num = Number<F>;

    fn mul(
        layouter: &mut impl Layouter<Self>,
        a: Self::Num,
        b: Self::Num,
    ) -> Result<Self::Num, Error> {
        let configured = layouter.configured().clone();
        let mut out = None;
        layouter.assign_region(
            || "mul",
            |mut region| {
                // We only want to use a single multiplication gate in this region,
                // so we enable it at region offset 0; this means it will constrain
                // cells at offsets 0 and 1.
                configured.s_mul.enable(&mut region, 0)?;

                // The inputs we've been given could be located anywhere in the circuit,
                // but we can only rely on relative offsets inside this region. So we
                // assign new cells inside the region and constrain them to have the
                // same values as the inputs.
                let lhs = region.assign_advice(
                    || "lhs",
                    configured.advice[0],
                    0,
                    || a.value.ok_or(Error::SynthesisError),
                )?;
                let rhs = region.assign_advice(
                    || "rhs",
                    configured.advice[1],
                    0,
                    || b.value.ok_or(Error::SynthesisError),
                )?;
                region.constrain_equal(&configured.perm, a.cell, lhs)?;
                region.constrain_equal(&configured.perm, b.cell, rhs)?;

                // Now we can assign the multiplication result into the output position.
                let value = a.value.and_then(|a| b.value.map(|b| a * b));
                let cell = region.assign_advice(
                    || "lhs * rhs",
                    configured.advice[0],
                    1,
                    || value.ok_or(Error::SynthesisError),
                )?;

                // Finally, we return a variable representing the output,
                // to be used in another part of the circuit.
                out = Some(Number { cell, value });
                Ok(())
            },
        )?;

        Ok(out.unwrap())
    }
}
// ANCHOR_END: mul-instructions-impl

// ANCHOR: circuit
/// The full circuit implementation.
///
/// In this struct we store the private input variables. We use `Option<F>` because
/// they won't have any value during key generation. During proving, if any of these
/// were `None` we would get an error.
struct MyCircuit<F: FieldExt> {
    a: Option<F>,
    b: Option<F>,
}

impl<F: FieldExt> Circuit<F> for MyCircuit<F> {
    // Since we are using a single chip for everything, we can just reuse its configured.
    type Configured = FieldConfigured;

    fn configure(meta: &mut ConstraintSystem<F>) -> Self::Configured {
        // We create the two advice columns that FieldChip uses for I/O.
        let advice = [meta.advice_column(), meta.advice_column()];

        // We also need an instance column to store public inputs.
        let instance = meta.instance_column();

        FieldConfig::configure(meta, advice, instance)
    }

    fn synthesize(
        &self,
        cs: &mut impl Assignment<F>,
        configured: Self::Configured,
    ) -> Result<(), Error> {
        let mut layouter = SingleConfigLayouter::new(cs, configured)?;

        // Load our private values into the circuit.
        let a = FieldConfig::<F>::load_private(&mut layouter, self.a)?;
        let b = FieldConfig::<F>::load_private(&mut layouter, self.b)?;

        // ab = a*b
        let ab = FieldConfig::<F>::mul(&mut layouter, a, b)?;
        // c = 2*a*b
        let c = FieldConfig::<F>::add(&mut layouter, ab.clone(), ab)?;

        // Expose the result as a public input to the circuit.
        FieldConfig::expose_public(&mut layouter, c)
    }
}
// ANCHOR_END: circuit

fn main() {
    use halo2::{dev::MockProver, pasta::Fp};

    // ANCHOR: test-circuit
    // The number of rows in our circuit cannot exceed 2^k. Since our example
    // circuit is very small, we can pick a very small value here.
    let k = 6;

    // Prepare the private and public inputs to the circuit!
    let a = Fp::from(2);
    let b = Fp::from(3);
    let c = a * b + a * b;

    // Instantiate the circuit with the private inputs.
    let circuit = MyCircuit {
        a: Some(a),
        b: Some(b),
    };

    // Arrange the public input. We expose the multiplication result in row 6
    // of the instance column, so we position it there in our public inputs.
    let mut public_inputs = vec![Fp::zero(); 1 << k];
    public_inputs[6] = c;

    // Given the correct public input, our circuit will verify.
    let prover = MockProver::run(k, &circuit, vec![public_inputs.clone()]).unwrap();
    assert_eq!(prover.verify(), Ok(()));

    // If we try some other public input, the proof will fail!
    public_inputs[6] += Fp::one();
    let prover = MockProver::run(k, &circuit, vec![public_inputs]).unwrap();
    assert_eq!(
        prover.verify(),
        Err(VerifyFailure::Gate {
            gate_index: 1,
            gate_name: "public input",
            row: 6,
        })
    );
    // ANCHOR_END: test-circuit
}
