use core::cmp::max;

use ff::Field;

use crate::poly::Rotation;

use super::{compress_selectors, Any, Column, ConstraintSystem, Expression, Fixed, FixedQuery};

/// One selector's compressed-column assignment: selector index, combination index,
/// and assigned root.
pub type SelectorAssignment = (usize, usize, usize);

/// Selector-compression fixture data: the original fixed-column count, packed columns,
/// and selector assignments.
pub type SelectorAssignmentData<F> = (usize, Vec<Vec<F>>, Vec<SelectorAssignment>);

impl<F: Field> ConstraintSystem<F> {
    /// Lean-dump helper (Halo2-Clean VK matching): run selector
    /// compression on a copy, returning the pre-compression fixed-column count and the
    /// packed fixed-column contents (the combination assignments).
    pub fn lean_dump_compress_selectors(&self, selectors: Vec<Vec<bool>>) -> (usize, Vec<Vec<F>>) {
        let cs = self.clone();
        let before = cs.num_fixed_columns;
        let (_cs2, polys) = cs.compress_selectors(selectors);
        (before, polys)
    }

    /// Lean-dump helper: the compressed CS after `compress_selectors` on a
    /// clone (the keygen transformation), for symbolic post-fixture dumping.
    pub fn lean_dump_compressed(&self, selectors: Vec<Vec<bool>>) -> ConstraintSystem<F> {
        let cs = self.clone();
        let (cs2, _polys) = cs.compress_selectors(selectors);
        cs2
    }

    /// Lean-dump helper with a caller-selected compilation environment. This keeps the
    /// symbolic serializer independent of the repository that owns `FixtureTypes` while
    /// allowing byte-exact checked-in fixtures (for example Ironwood's `Zcash.Circuits`
    /// namespace) to be regenerated directly.
    pub fn lean_dump_cs_fixture_in(
        &self,
        fixture_name: &str,
        fixture_import: &str,
        fixture_namespace: &str,
        open_namespace: &str,
        fmt_f: &dyn Fn(&F) -> String,
    ) -> String {
        fn fmt_expr<F: Field>(e: &Expression<F>, fmt_f: &dyn Fn(&F) -> String) -> String {
            match e {
                Expression::Constant(c) => format!("(.constant ({}))", fmt_f(c)),
                Expression::Selector(s) => format!("(.selector {})", s.0),
                Expression::Fixed(q) => format!("(.fixed {})", q.index),
                Expression::Advice(q) => format!("(.advice {})", q.index),
                Expression::Instance(q) => format!("(.instance {})", q.index),
                Expression::Negated(a) => format!("(.negated {})", fmt_expr(a, fmt_f)),
                Expression::Sum(a, b) => {
                    format!("(.sum {} {})", fmt_expr(a, fmt_f), fmt_expr(b, fmt_f))
                }
                Expression::Product(a, b) => {
                    format!("(.product {} {})", fmt_expr(a, fmt_f), fmt_expr(b, fmt_f))
                }
                Expression::Scaled(a, c) => {
                    format!("(.scaled {} ({}))", fmt_expr(a, fmt_f), fmt_f(c))
                }
            }
        }
        let advice_ql: Vec<String> = self
            .advice_queries
            .iter()
            .map(|(c, r)| format!("({}, {})", c.index(), r.0))
            .collect();
        let fixed_ql: Vec<String> = self
            .fixed_queries
            .iter()
            .map(|(c, r)| format!("({}, {})", c.index(), r.0))
            .collect();
        let instance_ql: Vec<String> = self
            .instance_queries
            .iter()
            .map(|(c, r)| format!("({}, {})", c.index(), r.0))
            .collect();
        let gates: Vec<String> = self
            .gates
            .iter()
            .flat_map(|g| g.polys.iter())
            .map(|p| fmt_expr(p, fmt_f))
            .collect();
        let lookups: Vec<String> = self
            .lookups
            .iter()
            .map(|l| {
                let ins: Vec<String> = l
                    .input_expressions
                    .iter()
                    .map(|e| fmt_expr(e, fmt_f))
                    .collect();
                let tbs: Vec<String> = l
                    .table_expressions
                    .iter()
                    .map(|e| fmt_expr(e, fmt_f))
                    .collect();
                format!(
                    "({{ inputs := [{}], tables := [{}] }} : LookupFixture)",
                    ins.join(", "),
                    tbs.join(", ")
                )
            })
            .collect();
        let lookups_field = if lookups.is_empty() {
            String::new()
        } else {
            format!(
                ",
    lookups := [{}]",
                lookups.join(
                    ",
      "
                )
            )
        };
        format!(
            "-- Auto-generated by halo2 `dump_lean` (Halo2-Clean VK-matching). Do not edit by hand.
import {}

namespace {}

open {}

def {} : CsFixture :=
  {{ numAdviceColumns := {},
    numFixedColumns := {},
    numInstanceColumns := {},
    numSelectors := {},
    adviceQueryLayout := [{}],
    fixedQueryLayout := [{}],
    instanceQueryLayout := [{}],
    gates := [{}]{} }}

end {}
",
            fixture_import,
            fixture_namespace,
            open_namespace,
            fixture_name,
            self.num_advice_columns,
            self.num_fixed_columns,
            self.num_instance_columns,
            self.num_selectors,
            advice_ql.join(", "),
            fixed_ql.join(", "),
            instance_ql.join(", "),
            gates.join(
                ",
      "
            ),
            lookups_field,
            fixture_namespace,
        )
    }

    /// Emit the compressed constraint-system projection in Ironwood's compact JSON
    /// fixture schema. `fmt_f` must return the canonical decimal representation of a
    /// field element; JSON stores field constants as strings to avoid integer limits.
    pub fn lean_dump_cs_fixture_json(&self, fmt_f: &dyn Fn(&F) -> String) -> String {
        fn fmt_expr<F: Field>(expression: &Expression<F>, fmt_f: &dyn Fn(&F) -> String) -> String {
            match expression {
                Expression::Constant(constant) => {
                    format!("[\"c\",\"{}\"]", fmt_f(constant))
                }
                Expression::Selector(selector) => format!("[\"sel\",{}]", selector.0),
                Expression::Fixed(query) => format!("[\"f\",{}]", query.index),
                Expression::Advice(query) => format!("[\"a\",{}]", query.index),
                Expression::Instance(query) => format!("[\"i\",{}]", query.index),
                Expression::Negated(inner) => {
                    format!("[\"neg\",{}]", fmt_expr(inner, fmt_f))
                }
                Expression::Sum(left, right) => format!(
                    "[\"+\",{},{}]",
                    fmt_expr(left, fmt_f),
                    fmt_expr(right, fmt_f)
                ),
                Expression::Product(left, right) => format!(
                    "[\"*\",{},{}]",
                    fmt_expr(left, fmt_f),
                    fmt_expr(right, fmt_f)
                ),
                Expression::Scaled(inner, scalar) => {
                    format!("[\"s\",{},\"{}\"]", fmt_expr(inner, fmt_f), fmt_f(scalar))
                }
            }
        }

        let advice_queries = self
            .advice_queries
            .iter()
            .map(|(column, rotation)| format!("[{},{}]", column.index(), rotation.0))
            .collect::<Vec<_>>()
            .join(",");
        let fixed_queries = self
            .fixed_queries
            .iter()
            .map(|(column, rotation)| format!("[{},{}]", column.index(), rotation.0))
            .collect::<Vec<_>>()
            .join(",");
        let instance_queries = self
            .instance_queries
            .iter()
            .map(|(column, rotation)| format!("[{},{}]", column.index(), rotation.0))
            .collect::<Vec<_>>()
            .join(",");
        let gates = self
            .gates
            .iter()
            .flat_map(|gate| gate.polys.iter())
            .map(|expression| fmt_expr(expression, fmt_f))
            .collect::<Vec<_>>()
            .join(",");
        let lookups = self
            .lookups
            .iter()
            .map(|lookup| {
                let inputs = lookup
                    .input_expressions
                    .iter()
                    .map(|expression| fmt_expr(expression, fmt_f))
                    .collect::<Vec<_>>()
                    .join(",");
                let tables = lookup
                    .table_expressions
                    .iter()
                    .map(|expression| fmt_expr(expression, fmt_f))
                    .collect::<Vec<_>>()
                    .join(",");
                format!("{{\"inputs\":[{}],\"tables\":[{}]}}", inputs, tables)
            })
            .collect::<Vec<_>>()
            .join(",");

        format!(
            "{{\"adviceQueryLayout\":[{}],\"fixedQueryLayout\":[{}],\"gates\":[{}],\"instanceQueryLayout\":[{}],\"lookups\":[{}],\"numAdviceColumns\":{},\"numFixedColumns\":{},\"numInstanceColumns\":{},\"numSelectors\":{}}}",
            advice_queries,
            fixed_queries,
            gates,
            instance_queries,
            lookups,
            self.num_advice_columns,
            self.num_fixed_columns,
            self.num_instance_columns,
            self.num_selectors,
        )
    }

    /// Lean-dump helper: the permutation columns in registration order.
    pub fn lean_dump_permutation_columns(&self) -> Vec<Column<Any>> {
        self.permutation.get_columns()
    }

    /// Lean-dump helper: the constants columns.
    pub fn lean_dump_constants(&self) -> Vec<Column<Fixed>> {
        self.constants.clone()
    }

    /// Lean-dump helper: number of selectors.
    pub fn lean_dump_num_selectors(&self) -> usize {
        self.num_selectors
    }

    /// Lean-dump helper: blinding factors (usable rows = n - (this + 1)).
    pub fn lean_dump_blinding_factors(&self) -> usize {
        self.blinding_factors()
    }

    /// Lean-dump helper: replicate `compress_selectors`'s setup and return
    /// `(num_fixed_before, packed_columns, assignments)` where each assignment is
    /// `(selector, combination_index, assigned_root)` (root extracted from the
    /// substitution expression `q·Π(Const(i)−q)`: the missing `i`).
    pub fn lean_dump_selector_assignments(
        &self,
        selectors: Vec<Vec<bool>>,
    ) -> SelectorAssignmentData<F> {
        let mut cs = self.clone();
        let before = cs.num_fixed_columns;
        let mut degrees = vec![0; selectors.len()];
        for expr in cs.gates.iter().flat_map(|gate| gate.polys.iter()) {
            if let Some(selector) = expr.extract_simple_selector() {
                degrees[selector.0] = max(degrees[selector.0], expr.degree());
            }
        }
        let max_degree = cs.degree();
        let mut new_columns = vec![];
        let (polys, selector_assignment) = compress_selectors::process(
            selectors
                .into_iter()
                .zip(degrees)
                .enumerate()
                .map(
                    |(i, (activations, max_degree))| compress_selectors::SelectorDescription {
                        selector: i,
                        activations,
                        max_degree,
                    },
                )
                .collect(),
            max_degree,
            || {
                let column = cs.fixed_column();
                new_columns.push(column);
                Expression::Fixed(FixedQuery {
                    index: cs.query_fixed_index(column),
                    column_index: column.index,
                    rotation: Rotation::cur(),
                })
            },
        );
        fn collect_consts<F: Field>(e: &Expression<F>, out: &mut Vec<F>) {
            match e {
                Expression::Product(x, y) | Expression::Sum(x, y) => {
                    collect_consts(x, out);
                    collect_consts(y, out);
                }
                Expression::Negated(x) => collect_consts(x, out),
                Expression::Scaled(x, _) => collect_consts(x, out),
                Expression::Constant(c) => out.push(*c),
                _ => {}
            }
        }
        let asn = selector_assignment
            .iter()
            .map(|a| {
                let mut consts = vec![];
                collect_consts(&a.expression, &mut consts);
                let len = consts.len() + 1;
                let root = {
                    let mut root_val = F::ONE;
                    let mut found = 1usize;
                    for i in 1..=len {
                        if !consts.contains(&root_val) {
                            found = i;
                            break;
                        }
                        root_val += F::ONE;
                    }
                    found
                };
                (a.selector, a.combination_index, root)
            })
            .collect();
        (before, polys, asn)
    }
}
