use std::iter;
use std::marker::PhantomData;

use halo2::arithmetic::FieldExt;

pub(crate) mod grain;
pub(crate) mod mds;

#[cfg(test)]
mod test_vectors;

use grain::SboxType;

/// A specification for a Poseidon permutation.
pub trait Spec<F: FieldExt> {
    /// The arity of this specification.
    fn arity() -> usize;

    /// The number of full rounds for this specification.
    fn full_rounds() -> usize;

    /// The number of partial rounds for this specification.
    fn partial_rounds() -> usize;

    /// The S-box for this specification.
    fn sbox(val: F) -> F;

    /// Side-loaded index of the first correct and secure MDS that will be generated by
    /// the reference implementation.
    ///
    /// This is used by the default implementation of [`Spec::constants`]. If you are
    /// hard-coding the constants, you may leave this unimplemented.
    fn secure_mds(&self) -> usize;

    /// Generates `(round_constants, mds, mds^-1)` corresponding to this specification.
    fn constants(&self) -> (Vec<Vec<F>>, Vec<Vec<F>>, Vec<Vec<F>>) {
        let t = Self::arity();
        let r_f = Self::full_rounds();
        let r_p = Self::partial_rounds();

        let mut grain = grain::Grain::new(SboxType::Pow, t as u16, r_f as u16, r_p as u16);

        let round_constants = (0..(r_f + r_p))
            .map(|_| (0..t).map(|_| grain.next_field_element()).collect())
            .collect();

        let (mds, mds_inv) = mds::generate_mds(&mut grain, t, self.secure_mds());

        (round_constants, mds, mds_inv)
    }
}

/// Poseidon-256 with arity 3, using the `x^5` S-box.
#[derive(Debug)]
pub struct P256Pow5T3<F: FieldExt> {
    secure_mds: usize,
    _field: PhantomData<F>,
}

impl<F: FieldExt> P256Pow5T3<F> {
    pub fn new(secure_mds: usize) -> Self {
        P256Pow5T3 {
            secure_mds,
            _field: PhantomData::default(),
        }
    }
}

impl<F: FieldExt> Spec<F> for P256Pow5T3<F> {
    fn arity() -> usize {
        3
    }

    fn full_rounds() -> usize {
        8
    }

    fn partial_rounds() -> usize {
        120
    }

    fn sbox(val: F) -> F {
        val.pow_vartime(&[5])
    }

    fn secure_mds(&self) -> usize {
        self.secure_mds
    }
}

/// Runs the Poseidon permutation on the given state.
fn permute<F: FieldExt, S: Spec<F>>(state: &mut [F], mds: &[Vec<F>], round_constants: &[Vec<F>]) {
    // TODO: Remove this when we can use const generics.
    assert!(state.len() == S::arity());

    let r_f = S::full_rounds() / 2;
    let r_p = S::partial_rounds();

    let apply_mds = |state: &mut [F]| {
        let new_state: Vec<_> = mds
            .iter()
            .map(|mds_row| {
                mds_row
                    .iter()
                    .zip(state.iter())
                    .fold(F::zero(), |acc, (mds, word)| acc + *mds * *word)
            })
            .collect();
        for (word, new_word) in state.iter_mut().zip(new_state.into_iter()) {
            *word = new_word;
        }
    };

    let full_round = |state: &mut [F], rcs: &[F]| {
        for (word, rc) in state.iter_mut().zip(rcs.iter()) {
            *word = S::sbox(*word + rc);
        }
        apply_mds(state);
    };

    let part_round = |state: &mut [F], rcs: &[F]| {
        for (word, rc) in state.iter_mut().zip(rcs.iter()) {
            *word += rc;
        }
        state[0] = S::sbox(state[0]);
        apply_mds(state);
    };

    iter::empty()
        .chain(iter::repeat(&full_round as &dyn Fn(&mut [F], &[F])).take(r_f))
        .chain(iter::repeat(&part_round as &dyn Fn(&mut [F], &[F])).take(r_p))
        .chain(iter::repeat(&full_round as &dyn Fn(&mut [F], &[F])).take(r_f))
        .zip(round_constants.iter())
        .fold(state, |state, (round, rcs)| {
            round(state, rcs);
            state
        });
}

fn pad_and_add<F: FieldExt>(state: &mut [F], input: &[F]) {
    let padding = state.len() - input.len();
    // TODO: Decide on a padding strategy (currently padding with all-ones)
    for (word, val) in state
        .iter_mut()
        .zip(input.iter().chain(iter::repeat(&F::one()).take(padding)))
    {
        *word += val;
    }
}

enum SpongeState<F: FieldExt> {
    Absorbing(Vec<F>),
    Squeezing(Vec<F>),
}

/// A Poseidon duplex sponge.
pub struct Duplex<F: FieldExt, S: Spec<F>> {
    sponge: Option<SpongeState<F>>,
    state: Vec<F>,
    rate: usize,
    mds_matrix: Vec<Vec<F>>,
    round_constants: Vec<Vec<F>>,
    _marker: PhantomData<S>,
}

impl<F: FieldExt, S: Spec<F>> Duplex<F, S> {
    /// Constructs a new duplex sponge with the given rate.
    pub fn new(spec: S, rate: usize) -> Self {
        assert!(rate < S::arity());

        let state = vec![F::zero(); S::arity()];
        let (round_constants, mds_matrix, _) = spec.constants();

        Duplex {
            sponge: Some(SpongeState::Absorbing(vec![])),
            state,
            rate,
            mds_matrix,
            round_constants,
            _marker: PhantomData::default(),
        }
    }

    fn process(&mut self, input: &[F]) -> Vec<F> {
        pad_and_add(&mut self.state[..self.rate], input);

        permute::<F, S>(&mut self.state, &self.mds_matrix, &self.round_constants);

        self.state[..self.rate].to_vec()
    }

    /// Absorbs an element into the sponge.
    pub fn absorb(&mut self, value: F) {
        match self.sponge.take().unwrap() {
            SpongeState::Absorbing(mut input) => {
                if input.len() < self.rate {
                    input.push(value);
                    self.sponge = Some(SpongeState::Absorbing(input));
                    return;
                }

                // We've already absorbed as many elements as we can
                let _ = self.process(&input);
                self.sponge = Some(SpongeState::Absorbing(vec![value]));
            }
            SpongeState::Squeezing(_) => {
                // Drop the remaining output elements
                self.sponge = Some(SpongeState::Absorbing(vec![value]));
            }
        }
    }

    /// Squeezes an element from the sponge.
    pub fn squeeze(&mut self) -> F {
        loop {
            match self.sponge.take().unwrap() {
                SpongeState::Absorbing(input) => {
                    self.sponge = Some(SpongeState::Squeezing(self.process(&input)));
                }
                SpongeState::Squeezing(mut output) => {
                    if !output.is_empty() {
                        let ret = output.remove(0);
                        self.sponge = Some(SpongeState::Squeezing(output));
                        return ret;
                    }

                    // We've already squeezed out all available elements
                    self.sponge = Some(SpongeState::Absorbing(vec![]));
                }
            }
        }
    }
}

/// A Poseidon hash function, built around a duplex sponge.
pub struct Hash<F: FieldExt, S: Spec<F>>(Duplex<F, S>);

impl<F: FieldExt, S: Spec<F>> Hash<F, S> {
    /// Initializes a new hasher.
    pub fn init(spec: S, rate: usize) -> Self {
        Hash(Duplex::new(spec, rate))
    }

    /// Updates the hasher with the given value.
    pub fn update(&mut self, value: F) {
        self.0.absorb(value);
    }

    /// Finalizes the hasher, returning its output.
    pub fn finalize(mut self) -> F {
        // TODO: Check which state element other implementations use.
        self.0.squeeze()
    }
}
