name: Audits

on:
  pull_request:
  push:
    branches: main

permissions:
  contents: read

jobs:
  cargo-vet:
    name: Vet Rust dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: dtolnay/rust-toolchain@3c5f7ea28cd621ae0bf5283f0e981fb97b8a7af9 # master HEAD 2026-05-31
        id: toolchain
        with:
          toolchain: stable
      - run: rustup override set "${TOOLCHAIN}"
        env:
          TOOLCHAIN: ${{steps.toolchain.outputs.name}}
      - run: cargo install cargo-vet --version ~0.10
      - run: cargo vet --locked
